In [58]:
#pip install torch

In [59]:
#pip install torch --no-cache-dir


In [60]:
#pip install tools

In [61]:
#pip install torch

In [62]:
#pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

In [63]:
import torch

In [64]:
t1 = torch.tensor(4.)

In [65]:
t1

tensor(4.)

In [66]:
t1.dtype

torch.float32

In [67]:
t2 = torch.tensor([1.,2.,3,4])

In [68]:
t2

tensor([1., 2., 3., 4.])

In [69]:
t2.dtype

torch.float32

In [70]:
t3 =  torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])

In [71]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [72]:
t3.dtype

torch.float32

In [73]:
t4 = torch.tensor([[[11,12,13],
                    [13,14,15]],
                   
                   [[16,17,18],
                    [19,20,21]]])

In [74]:
import numpy as np
a = np.zeros([2,3,3])

In [75]:
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]]])

In [76]:
a.ndim

3

In [77]:
t4.ndim

3

In [78]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
t4.shape

torch.Size([2, 2, 3])

In [80]:
a.shape

(2, 3, 3)

In [81]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad= True)
b = torch.tensor(5.,requires_grad = True)



In [82]:
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [83]:
y = x*w+b

In [84]:
y

tensor(17., grad_fn=<AddBackward0>)

In [85]:
#compute derviatives
y.backward()

In [86]:
#display gradients The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.
print('dy/dx:',x.grad)
print('dy/dw',w.grad)
print('dy/db:',b.grad)


dy/dx: None
dy/dw tensor(3.)
dy/db: tensor(1.)


In [87]:
y =  torch.from_numpy(a)

In [88]:
y

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [89]:
a.dtype,y.dtype

(dtype('float64'), torch.float64)

In [90]:
z = y.numpy()

In [91]:
z


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

What if one or more x, w or b were matrices, instead of numbers, in the above example? What would the result y and the gradients w.grad and b.grad look like in this case?

What if y was a matrix created using torch.tensor, with each element of the matrix expressed as a combination of numeric tensors x, w and b?

What if we had a chain of operations instead of just one i.e. y = x * w + b, z = l * y + m, w = c * z + d and so on? What would calling w.grad do?

In [92]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [93]:
inputs.shape

(5, 3)

In [94]:
inputs.ndim

2

In [95]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [96]:
targets.shape

(5, 2)

In [97]:
targets.ndim

2

In [98]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [99]:
#Weights and Biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad = True)
print(w)
print(b)


tensor([[ 1.5192, -1.3070,  0.7007],
        [ 0.4954,  0.3335, -1.2092]], requires_grad=True)
tensor([-1.8299,  0.6046], requires_grad=True)


In [100]:
def model(x):
    return x @ w.t() + b
#x - rainfall, temp, humidity - Inputs
#w - weights
#t() - transpose
#b  - biases

In [101]:
#Generate Predictions
preds = model(inputs)
print(preds)

tensor([[ 51.6329,   7.1113],
        [ 66.2467,  -2.3633],
        [ -4.1565,  18.2499],
        [122.8525,  20.7295],
        [ 26.5733, -17.8492]], grad_fn=<AddBackward0>)


In [102]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


#Loss Function
"Calculate the difference between the two matrices (preds and targets).
Square all elements of the difference matrix to remove negative values.
Calculate the average of the elements in the resulting matrix.
The result is a single number, known as the mean squared error (MSE)."

In [103]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [104]:
#compute loss
loss = mse(preds,targets)
print(loss)

tensor(7821.5498, grad_fn=<DivBackward0>)


In [105]:
import math
math.sqrt(loss)

88.43952625770618

In [106]:
#Compute Dertivatives/Grandient
loss.backward()

In [107]:
#Grdient weights
print(w)
print(w.grad)

tensor([[ 1.5192, -1.3070,  0.7007],
        [ 0.4954,  0.3335, -1.2092]], requires_grad=True)
tensor([[-1472.4889, -4218.8315, -1978.6791],
        [-7016.4761, -8504.6367, -5231.2852]])


In [108]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [109]:
#Generate Predictons
preds = model(inputs)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [110]:
#calculate loss
loss = mse(preds,targets)
print(loss)

tensor(7821.5498, grad_fn=<DivBackward0>)


In [111]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-1472.4889, -4218.8315, -1978.6791],
        [-7016.4761, -8504.6367, -5231.2852]])
tensor([-23.5702, -86.8244])


In [112]:
#Adjust weights and reset  gradients
#1e-5 - learning rate
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [117]:
w.dtype

torch.float32

In [118]:
w.grad.dtype

torch.float32

In [119]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
        

In [120]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(958.7391, grad_fn=<DivBackward0>)


In [121]:
# Predictions
preds

tensor([[ 68.3796,  76.2697],
        [ 93.7357,  92.0408],
        [ 74.4383, 143.0038],
        [ 88.4440,  69.7933],
        [ 82.3046,  85.1173]], grad_fn=<AddBackward0>)

In [122]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [123]:
import torch.nn as nn

In [124]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [125]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [126]:
from torch.utils.data import TensorDataset

In [127]:
train_ds = TensorDataset(inputs,targets)

In [128]:
train_ds

In [131]:
train_ds[0:1]

(tensor([[73., 67., 43.]]), tensor([[56., 70.]]))

In [133]:
from torch.utils.data import DataLoader

In [134]:
# define Data loader
batch_size =5
train_dl  = DataLoader(train_ds,batch_size,shuffle=True)
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 56.,  70.],
        [ 56.,  70.]])


In [135]:
#Define Model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.0940,  0.0220, -0.0437],
        [-0.5079, -0.1709,  0.3390]], requires_grad=True)
Parameter containing:
tensor([-0.3206,  0.3533], requires_grad=True)


In [136]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0940,  0.0220, -0.0437],
         [-0.5079, -0.1709,  0.3390]], requires_grad=True),
 Parameter containing:
 tensor([-0.3206,  0.3533], requires_grad=True)]

In [137]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -7.5847, -33.5946],
        [ -9.7314, -39.2061],
        [ -8.0812, -47.0719],
        [-10.5759, -46.2540],
        [ -7.7501, -27.3666],
        [ -7.5847, -33.5946],
        [ -9.7314, -39.2061],
        [ -8.0812, -47.0719],
        [-10.5759, -46.2540],
        [ -7.7501, -27.3666],
        [ -7.5847, -33.5946],
        [ -9.7314, -39.2061],
        [ -8.0812, -47.0719],
        [-10.5759, -46.2540],
        [ -7.7501, -27.3666]], grad_fn=<AddmmBackward>)

In [138]:
# Import nn.functional
import torch.nn.functional as F

In [139]:
# Define loss function
loss_fn = F.mse_loss

In [140]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(13292.1475, grad_fn=<MseLossBackward>)


In [141]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [142]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [145]:
fit(90, model, loss_fn, opt,train_dl)

Epoch [10/90], Loss: 5.2773
Epoch [20/90], Loss: 13.5452
Epoch [30/90], Loss: 7.2140
Epoch [40/90], Loss: 6.3001
Epoch [50/90], Loss: 5.6094
Epoch [60/90], Loss: 2.4867
Epoch [70/90], Loss: 7.5566
Epoch [80/90], Loss: 4.2814
Epoch [90/90], Loss: 3.9854


In [146]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.4442,  70.5240],
        [ 80.5763, 100.1885],
        [121.6812, 133.6333],
        [ 23.0459,  37.9143],
        [ 97.8939, 117.8513],
        [ 57.4442,  70.5240],
        [ 80.5763, 100.1885],
        [121.6812, 133.6333],
        [ 23.0459,  37.9143],
        [ 97.8939, 117.8513],
        [ 57.4442,  70.5240],
        [ 80.5763, 100.1885],
        [121.6812, 133.6333],
        [ 23.0459,  37.9143],
        [ 97.8939, 117.8513]], grad_fn=<AddmmBackward>)

In [147]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])